kind = "web"
previewPath = "/"
title = "SafePasSwordmaker"
version = "1.0.0"
id = "artifacts/safepasswordmaker"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18874

[services.development]
run = "pnpm --filter @workspace/safepasswordmaker run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/safepasswordmaker", "run", "build" ]
publicDir = "artifacts/safepasswordmaker/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18874"
BASE_PATH = "/"
